#!/bin/sh
# Upload file: server.crt
# Auto-generated by create-application
set -eu

upload_pre_start_file \
  "{{ upload_server_crt_content }}" \
  "{{ upload_server_crt_destination }}" \
  "server.crt" \
  "{{ shared_volpath }}" \
  "{{ hostname }}" \
  "{{ uid }}" \
  "{{ gid }}" \
  "{{ mapped_uid }}" \
  "{{ mapped_gid }}"

upload_output_result "upload_server_crt_uploaded"
