#!/bin/sh
# Upload file: Nginx Configuration Fil
# Auto-generated by create-application
set -eu

upload_pre_start_file \
  "{{ upload_nginx_configuration_fil_content }}" \
  "{{ upload_nginx_configuration_fil_destination }}" \
  "Nginx Configuration Fil" \
  "{{ shared_volpath }}" \
  "{{ hostname }}" \
  "{{ uid }}" \
  "{{ gid }}" \
  "{{ mapped_uid }}" \
  "{{ mapped_gid }}"

upload_output_result "upload_nginx_configuration_fil_uploaded"
