/**
 * Single-snapshot manager for live integration tests.
 *
 * Creates a single whole-nested-VM snapshot via `qm snapshot` on the outer
 * PVE host (not pct snapshot inside the nested VM). This guarantees an
 * atomic ZFS snapshot of vm-9002-disk-N, which captures all LXC rootfs,
 * all managed volumes, AND the storagecontext-backup on the nested-VM
 * host filesystem in one consistent state.
 *
 * Naming: `dep-stacks-ready` — created once after all stack-provider
 * scenarios (postgres/*, zitadel/*, nginx/*, etc.) have been installed,
 * reused as the rollback target for failed consumer tests.
 *
 * For dev instances (deployer runs locally on macOS), the local context
 * files (storagecontext.json, secret.txt) are copied to the nested VM
 * before snapshot creation and restored after rollback so the local
 * deployer's view stays consistent with the snapshot state.
 */
import { execSync } from "node:child_process";
import { existsSync, copyFileSync, readFileSync } from "node:fs";
import path from "node:path";

export interface SnapshotConfig {
  enabled: boolean;
}

const CONTEXT_BACKUP_DIR = "/root/.deployer-context-backup";

export class SnapshotManager {
  private debugIndex = 0;

  constructor(
    private outerPveHost: string,
    private nestedVmId: number,
    private nestedSshPort: number,
    private log: (msg: string) => void = console.log,
    private localContextPath?: string,
  ) {}

  /**
   * Save a copy of the storagecontext for debugging.
   * Only active when DEPLOYER_PLAINTEXT_CONTEXT=1.
   */
  private saveContextSnapshot(label: string): void {
    if (!this.localContextPath) return;
    const src = path.join(this.localContextPath, "storagecontext.json");
    if (!existsSync(src)) return;
    try {
      const head = readFileSync(src, "utf-8").slice(0, 4);
      if (head === "enc:") return;
    } catch { return; }
    try {
      const idx = String(this.debugIndex++).padStart(3, "0");
      const dest = path.join(this.localContextPath, `storagecontext-${idx}-${label}.json`);
      copyFileSync(src, dest);
      this.log(`Context snapshot saved: ${path.basename(dest)}`);
    } catch { /* ignore */ }
  }

  /** SSH to the outer PVE host (port 22) for qm commands */
  private outerSsh(cmd: string, timeout = 60000): string {
    return execSync(
      `ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o BatchMode=yes -o ConnectTimeout=10 root@${this.outerPveHost} ${JSON.stringify(cmd)}`,
      { timeout, encoding: "utf-8", stdio: ["pipe", "pipe", "pipe"] },
    ).trim();
  }

  /** SSH to the nested PVE VM (via port-forwarded port) */
  private nestedSsh(cmd: string, timeout = 15000): string {
    return execSync(
      `ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o BatchMode=yes -o ConnectTimeout=10 -p ${this.nestedSshPort} root@${this.outerPveHost} ${JSON.stringify(cmd)}`,
      { timeout, encoding: "utf-8", stdio: ["pipe", "pipe", "pipe"] },
    ).trim();
  }

  /** SCP files to the nested VM */
  private scpToNested(localFile: string, remotePath: string): void {
    execSync(
      `scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o BatchMode=yes -P ${this.nestedSshPort} ${JSON.stringify(localFile)} root@${this.outerPveHost}:${JSON.stringify(remotePath)}`,
      { timeout: 15000, encoding: "utf-8", stdio: ["pipe", "pipe", "pipe"] },
    );
  }

  /** SCP files from the nested VM */
  private scpFromNested(remotePath: string, localFile: string): void {
    execSync(
      `scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o BatchMode=yes -P ${this.nestedSshPort} root@${this.outerPveHost}:${JSON.stringify(remotePath)} ${JSON.stringify(localFile)}`,
      { timeout: 15000, encoding: "utf-8", stdio: ["pipe", "pipe", "pipe"] },
    );
  }

  /** Check if a host-PVE qm snapshot with this name exists for the nested VM */
  exists(name: string): boolean {
    try {
      this.outerSsh(
        `qm listsnapshot ${this.nestedVmId} | grep -q ' ${name} \\| ${name}$'`,
        15000,
      );
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Backup local deployer context files to the nested VM.
   * Called before snapshot creation so the snapshot embeds the latest
   * passwords/secrets generated by the local deployer.
   */
  private backupContext(): void {
    if (!this.localContextPath) return;

    const ctxFile = `${this.localContextPath}/storagecontext.json`;
    const secretFile = `${this.localContextPath}/secret.txt`;

    if (!existsSync(ctxFile) && !existsSync(secretFile)) return;

    try {
      this.nestedSsh(`mkdir -p ${CONTEXT_BACKUP_DIR}`);
      if (existsSync(ctxFile)) {
        this.scpToNested(ctxFile, `${CONTEXT_BACKUP_DIR}/storagecontext.json`);
      }
      if (existsSync(secretFile)) {
        this.scpToNested(secretFile, `${CONTEXT_BACKUP_DIR}/secret.txt`);
      }
      this.nestedSsh("sync");
      const verify = this.nestedSsh(`ls ${CONTEXT_BACKUP_DIR}/ 2>&1`);
      this.log(`Local context backed up to nested VM (${verify.replace(/\n/g, ", ")})`);
    } catch (err) {
      this.log(`Warning: context backup failed (non-fatal): ${err}`);
    }
  }

  /** Public wrapper for restoreContext (used for retry after failed reload) */
  restoreContextPublic(): void { this.restoreContext(); }

  private restoreContext(): void {
    if (!this.localContextPath) return;

    try {
      this.scpFromNested(
        `${CONTEXT_BACKUP_DIR}/storagecontext.json`,
        `${this.localContextPath}/storagecontext.json`,
      );
      this.scpFromNested(
        `${CONTEXT_BACKUP_DIR}/secret.txt`,
        `${this.localContextPath}/secret.txt`,
      );
      this.log("Local context restored from snapshot");
    } catch (err) {
      this.log(`Warning: context restore failed (non-fatal): ${err}`);
    }
  }

  /**
   * Create a whole-nested-VM snapshot on the outer PVE host.
   * Captures all LXC rootfs, managed volumes, and the nested-VM host FS
   * (including the storagecontext-backup dir) in one atomic ZFS snapshot.
   */
  createHostSnapshot(name: string, buildHash?: string): void {
    this.log(`Creating snapshot @${name}...`);

    this.saveContextSnapshot(`before-create-${name}`);
    this.backupContext();

    // Sync nested VM filesystem so the snapshot is consistent
    try { this.nestedSsh("sync", 10000); } catch { /* ignore */ }

    // Idempotent: drop existing snapshot with same name
    try {
      this.outerSsh(
        `qm delsnapshot ${this.nestedVmId} ${name} 2>/dev/null; true`,
        30000,
      );
    } catch { /* ignore */ }

    const desc = buildHash ? `build:${buildHash}` : "livetest";
    this.outerSsh(
      `qm snapshot ${this.nestedVmId} ${name} --vmstate 0 --description ${JSON.stringify(desc)}`,
      60000,
    );

    this.saveContextSnapshot(`after-create-${name}`);
    this.log(`Snapshot @${name} created`);
  }

  /**
   * Rollback to a whole-nested-VM snapshot on the outer PVE host.
   * Deletes any newer snapshots first (qm requires the target to be the most
   * recent), stops the VM, rolls back, restarts, waits for SSH, and restores
   * the local deployer context from the now-current snapshot state.
   */
  rollbackHostSnapshot(name: string): void {
    this.log(`Rolling back to @${name}...`);
    this.saveContextSnapshot(`before-rollback-${name}`);

    // Delete snapshots newer than target — qm rollback requires the target
    // snapshot to be the most recent one in the chain.
    try {
      const snapList = this.outerSsh(`qm listsnapshot ${this.nestedVmId}`, 15000);
      const allNames: string[] = [];
      for (const line of snapList.split("\n")) {
        const m = line.match(/[`|]\->\s+(\S+)/);
        if (m && m[1] !== "current") allNames.push(m[1]);
      }
      const targetIdx = allNames.indexOf(name);
      if (targetIdx >= 0) {
        for (let i = allNames.length - 1; i > targetIdx; i--) {
          this.log(`Deleting newer snapshot @${allNames[i]}`);
          try {
            this.outerSsh(`qm delsnapshot ${this.nestedVmId} ${allNames[i]}`, 30000);
          } catch { /* ignore */ }
        }
      }
    } catch {
      this.log("Warning: could not enumerate snapshots before rollback");
    }

    try {
      this.outerSsh(`qm stop ${this.nestedVmId}`, 60000);
    } catch {
      this.log("Warning: qm stop failed (may already be stopped)");
    }

    this.outerSsh(`qm rollback ${this.nestedVmId} ${name}`, 120000);
    this.outerSsh(`qm start ${this.nestedVmId}`, 30000);
    this.waitForNestedVm();

    this.restoreContext();
    this.saveContextSnapshot(`after-rollback-${name}`);
    this.log(`Rollback to @${name} complete`);
  }

  /**
   * Check if a snapshot's description matches the given build hash.
   * Used to invalidate dep-stacks-ready when the deployer build changed.
   */
  matchesBuild(name: string, buildHash?: string): boolean {
    if (!buildHash) return true;
    try {
      const output = this.outerSsh(`qm listsnapshot ${this.nestedVmId}`, 15000);
      for (const line of output.split("\n")) {
        if (line.includes(` ${name} `) || line.includes(` ${name}\t`)) {
          return line.includes(`build:${buildHash}`);
        }
      }
      return false;
    } catch {
      return false;
    }
  }

  /** Wait for the nested VM to become reachable via SSH after boot */
  private waitForNestedVm(timeoutMs = 120000): void {
    const start = Date.now();
    while (Date.now() - start < timeoutMs) {
      try {
        this.nestedSsh("echo ok", 5000);
        this.sleep(5);
        return;
      } catch {
        this.sleep(3);
      }
    }
    throw new Error(`Nested VM not reachable via SSH after ${timeoutMs / 1000}s`);
  }

  private sleep(seconds: number): void {
    execSync(`sleep ${seconds}`, { stdio: "ignore" });
  }
}
