import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatRadioModule } from '@angular/material/radio';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';

import { CreateApplicationStateService } from '../services/create-application-state.service';

@Component({
  selector: 'app-ssl-step',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatIconModule,
    MatRadioModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatInputModule
  ],
  template: `
    <div class="ssl-step" data-testid="ssl-step">
      <mat-card>
        <mat-card-header>
          <mat-card-title>
            <mat-icon>lock</mat-icon>
            SSL / HTTPS Configuration
          </mat-card-title>
        </mat-card-header>
        <mat-card-content>
          <p class="description">
            Configure how this application handles HTTPS and TLS certificates.
            When the SSL addon is enabled during installation, certificates are
            automatically generated by the deployer's built-in Certificate Authority.
            Only settings that differ from the defaults are saved.
          </p>

          <!-- SSL Mode -->
          <div class="ssl-section">
            <h3>SSL Mode</h3>
            <mat-radio-group
              [value]="state.sslMode()"
              (change)="state.sslMode.set($event.value)"
              class="mode-group"
              data-testid="ssl-mode-group">

              <div class="mode-option">
                <mat-radio-button value="proxy">
                  <span class="mode-label">Proxy (nginx)</span>
                  <span class="mode-default">Default</span>
                </mat-radio-button>
                <p class="mode-description">
                  An nginx reverse proxy is automatically installed in the container.
                  It terminates HTTPS and forwards traffic to the application's HTTP port.
                  The application itself does not need to handle TLS.
                </p>
              </div>

              <div class="mode-option">
                <mat-radio-button value="native">
                  <span class="mode-label">Native</span>
                </mat-radio-button>
                <p class="mode-description">
                  The application handles HTTPS itself. Certificates are generated and
                  mounted into the container, but no proxy is installed. The application
                  must be configured to read the certificate files.
                </p>
              </div>

              <div class="mode-option">
                <mat-radio-button value="certs">
                  <span class="mode-label">Certificates only</span>
                </mat-radio-button>
                <p class="mode-description">
                  Only generates and provisions certificates — no proxy, no port configuration.
                  Use this when the application needs certificates for non-HTTPS purposes
                  (e.g., database TLS, MQTT TLS).
                </p>
              </div>
            </mat-radio-group>
          </div>

          <!-- Certificate Types -->
          <div class="ssl-section">
            <h3>Certificate Files</h3>
            <p class="section-description">
              Choose which certificate files should be generated and placed in the container.
              Files follow the Let's Encrypt naming convention.
            </p>

            <div class="cert-option">
              <mat-checkbox
                [checked]="state.sslNeedsServerCert()"
                (change)="state.sslNeedsServerCert.set($event.checked)"
                data-testid="ssl-server-cert-checkbox">
                Server Certificate
              </mat-checkbox>
              <p class="cert-description">
                Generates <code>privkey.pem</code> (private key), <code>cert.pem</code> (certificate),
                and <code>fullchain.pem</code> (certificate + CA chain).
                Required for HTTPS in proxy and native mode.
              </p>
            </div>

            <div class="cert-option">
              <mat-checkbox
                [checked]="state.sslNeedsCaCert()"
                (change)="state.sslNeedsCaCert.set($event.checked)"
                data-testid="ssl-ca-cert-checkbox">
                CA Certificate
              </mat-checkbox>
              <p class="cert-description">
                Writes <code>chain.pem</code> (CA public certificate) into the container.
                Needed when the application must verify certificates signed by the same CA
                (e.g., a database client verifying the server's certificate).
              </p>
            </div>
          </div>

          <!-- Volume Configuration -->
          <div class="ssl-section">
            <h3>Certificate Volume</h3>
            <p class="section-description">
              Where certificates are mounted inside the container, with permissions and ownership.
            </p>
            <mat-form-field appearance="fill" class="volume-field">
              <mat-label>Volume</mat-label>
              <input matInput
                     [ngModel]="state.sslAddonVolumes()"
                     (ngModelChange)="state.sslAddonVolumes.set($event)"
                     placeholder="certs=/etc/ssl/addon,0700,0:0"
                     data-testid="ssl-addon-volumes-input" />
              <mat-hint>Format: key=path,mode,uid:gid — only saved if changed from default</mat-hint>
            </mat-form-field>

            <div class="volume-examples">
              <p><strong>Examples:</strong></p>
              <p><code>certs=/etc/ssl/addon,0700,0:0</code> — Default, root-owned</p>
              <p><code>certs=/certs,0700,70:70</code> — Postgres user (UID 70)</p>
              <p><code>certs=certs,0700,0:0</code> — Relative path (Docker volume)</p>
            </div>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: [`
    .ssl-step {
      padding: 1rem 0;
    }

    mat-card-title {
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }

    .description {
      margin-bottom: 1.5rem;
      color: rgba(0, 0, 0, 0.6);
    }

    .ssl-section {
      margin-bottom: 1.5rem;

      h3 {
        margin: 0 0 0.5rem 0;
        font-size: 1rem;
        font-weight: 500;
        color: rgba(0, 0, 0, 0.87);
      }
    }

    .section-description {
      margin: 0 0 0.75rem 0;
      font-size: 0.85rem;
      color: rgba(0, 0, 0, 0.6);
    }

    /* Mode radio buttons */
    .mode-group {
      display: flex;
      flex-direction: column;
      gap: 0.25rem;
    }

    .mode-option {
      padding: 0.75rem 1rem;
      border: 1px solid #e0e0e0;
      border-radius: 8px;
      margin-bottom: 0.5rem;
      background: #fafafa;

      &:has(mat-radio-button.mat-mdc-radio-checked) {
        border-color: #1976d2;
        background: #e3f2fd;
      }
    }

    .mode-label {
      font-weight: 500;
    }

    .mode-default {
      margin-left: 0.5rem;
      font-size: 0.75rem;
      color: rgba(0, 0, 0, 0.4);
      font-style: italic;
    }

    .mode-description {
      margin: 0.25rem 0 0 2rem;
      font-size: 0.82rem;
      color: rgba(0, 0, 0, 0.6);
      line-height: 1.4;
    }

    /* Certificate checkboxes */
    .cert-option {
      padding: 0.5rem 1rem;
      border: 1px solid #e0e0e0;
      border-radius: 8px;
      margin-bottom: 0.5rem;
      background: #fafafa;
    }

    .cert-description {
      margin: 0.25rem 0 0 2rem;
      font-size: 0.82rem;
      color: rgba(0, 0, 0, 0.6);
      line-height: 1.4;

      code {
        background: #e8eaf6;
        padding: 1px 4px;
        border-radius: 3px;
        font-size: 0.8rem;
      }
    }

    /* Volume */
    .volume-field {
      width: 100%;
      margin-top: 0.25rem;
    }

    .volume-examples {
      margin-top: 0.75rem;
      padding: 0.75rem 1rem;
      background: #f5f5f5;
      border-radius: 8px;
      border-left: 4px solid #90a4ae;

      p {
        margin: 0 0 0.25rem 0;
        font-size: 0.82rem;
        color: #37474f;
        line-height: 1.5;

        &:last-child {
          margin-bottom: 0;
        }
      }

      code {
        background: #e0e0e0;
        padding: 1px 4px;
        border-radius: 3px;
        font-size: 0.78rem;
      }
    }
  `]
})
export class SslStepComponent {
  readonly state = inject(CreateApplicationStateService);
}
